global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sentiment-model'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: sentiment-model
          environment: production